using System;

namespace PartialClassDemo
{
    // ==========================================================
    // SIMULATED FILE 1: Employee_Core.cs
    // (Perhaps auto-generated by a database tool)
    // ==========================================================
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public void DisplayBasicInfo()
        {
            Console.WriteLine($"[ID: {EmployeeId}] {FirstName} {LastName}");
        }
    }

    // ==========================================================
    // SIMULATED FILE 2: Employee_Logic.cs
    // (Where a developer writes custom business logic)
    // ==========================================================
    public partial class Employee
    {
        public double BaseSalary { get; set; }
        public double Bonus { get; set; }

        // This method lives in "File 2", but it can access properties 
        // like 'FirstName' that were defined in "File 1"!
        public void CalculateTotalCompensation()
        {
            double total = BaseSalary + Bonus;
            Console.WriteLine($"Total Compensation for {FirstName}: ${total}");
        }
    }

    // ==========================================================
    // MAIN EXECUTION FILE: Program.cs
    // ==========================================================
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("--- Partial Class Demo ---\n");

            // Even though the properties and methods were defined in two separate blocks,
            // the 'myEmployee' object has access to ALL of them seamlessly.
            Employee myEmployee = new Employee();

            // Properties from Part 1
            myEmployee.EmployeeId = 1001;
            myEmployee.FirstName = "Tanishqa";
            myEmployee.LastName = "Dayma";

            // Properties from Part 2
            myEmployee.BaseSalary = 85000;
            myEmployee.Bonus = 15000;

            // Calling methods from both parts
            myEmployee.DisplayBasicInfo();
            myEmployee.CalculateTotalCompensation();

            Console.WriteLine("\n--- End of Demo ---");
        }
    }
}